### ISSUE TITLE
Item selection color using keyboard keys 

### ISSUE THREAD

**Issue by ehazan** [EvroHQ/EvroDark#2]
Is it possible to do this background color selection more clear?
I'm using keyboard keys here
It is hardly seen on this background

<img width="625" alt="Screenshot 2024-06-26 at 9 04 37 AM" src="https://github.com/EvroHQ/EvroDark/assets/23287078/ffdc036e-7de2-4332-8c86-a282643b87a2">

**Comment by EvroHQ** [comment]
Hi Ehazan, Will Check that tonight 👌

**Comment by EvroHQ** [comment]
done

**Comment by ehazan** [comment]
Thanks a lot.
Best theme ever!

**Comment by EvroHQ** [comment]
Thanks mate, with pleasure ❤️

**Comment by EvroHQ** [comment]
## Write a review:
https://marketplace.visualstudio.com/items?itemName=EvroHQ.evro-dark&ssr=false#review-details

Thanks for improving the theme!
